import { Navigation, DemoBar, Photo, Form, Location, Testimonials, Footer, Arrow } from "./Experience";

export default function Barber() { return <main className="blackhousePage"><DemoBar name="Black House"/><Navigation brand="BLACK HOUSE" home="/exemplos/barbearia" links={[["Serviços", "#servicos"], ["A casa", "#experiencia"], ["Barbeiros", "#equipe"], ["Contato", "#contato"]]} action="#agenda" actionLabel="Agendar horário"/>
  <section className="barberHero"><div><span className="eyebrow">BARBEARIA & BOAS CONVERSAS · EST. 1984</span><h1>O clássico<br/>nunca perde<br/><em>o estilo.</em></h1><p>Corte preciso. Toalha quente. Seu disco favorito.<br/>Reserve um momento para cuidar de você.</p><a className="refinedBtn" href="#agenda">Escolher meu horário<Arrow/></a><div className="barberSeal">BH<span>FEITO COM TEMPO<br/>E PERSONALIDADE</span></div></div><Photo id="12505400" alt="Interior de barbearia com atmosfera vintage" eager/></section>
  <div className="barberRibbon">CORTE CLÁSSICO <span>✦</span> BARBA NA NAVALHA <span>✦</span> ESTILO SEM PRESSA <span>✦</span> BLACK HOUSE</div>
  <section className="barberServices" id="servicos"><div><span className="eyebrow">O RITUAL</span><h2>Bom gosto.<br/>Bom acabamento.</h2><p>O cuidado está nos detalhes, do diagnóstico do corte à finalização.</p></div><div>{[["01", "Corte clássico", "Tesoura, máquina e acabamento sob medida.", "45 min", "55"], ["02", "Barba completa", "Toalha quente, navalha e hidratação.", "30 min", "45"], ["03", "Ritual Black House", "Cabelo e barba, com tempo para fazer direito.", "75 min", "90"]].map(([n, t, d, time, price]) => <a className="barberServiceRow" key={n} href="#agenda"><span>{n}</span><div><h3>{t}</h3><p>{d}</p><small>{time}</small></div><strong>R$ {price} ↗</strong></a>)}</div></section>
  <section className="barberStory" id="experiencia"><Photo id="7697391" alt="Barbeiro recebe os clientes junto à cadeira de atendimento"/><div><span className="eyebrow">ENTRE. SENTE. SINTA-SE EM CASA.</span><h2>Madeira, vinil<br/>e histórias<br/><em>para contar.</em></h2><p>Inspirada no espírito das barbearias dos anos 70 e 80, a Black House combina um ambiente acolhedor com técnica atual. Aqui, seu estilo é ouvido antes de ser desenhado.</p></div></section>
  <section className="barberTeam" id="equipe"><span className="eyebrow">QUEM CUIDA DO SEU ESTILO</span><h2>Mãos experientes.<br/>Personalidades próprias.</h2><div className="barberTeamGrid">{[["7697391", "André", "Cortes clássicos & tesoura"], ["1805600", "Rafael", "Barba & acabamento"]].map(([id, name, role]) => <article key={name}><Photo id={id} alt={`Imagem ilustrativa de atendimento da equipe — ${name}`}/><h3>{name}</h3><p>{role}</p></article>)}</div></section>
  <section className="barberGallery"><div><span className="eyebrow">DETALHES DA CASA</span><h2>Seu tempo merece<br/>um bom lugar.</h2></div><Photo id="1895701" alt="Ambiente com tijolos aparentes, madeira e luz natural"/><Photo id="12505400" alt="Cadeira clássica e instrumentos da barbearia"/></section>
  <Testimonials quotes={[["O corte ficou exatamente como conversamos. Atendimento sem correria.", "Bruno S."], ["Toalha quente, boa música e acabamento impecável.", "Felipe R."], ["Um ambiente de outra época, com cuidado de hoje.", "Daniel M."]]}/>
  <section id="agenda" className="experienceContact"><div><span className="eyebrow">RESERVE SEU MOMENTO</span><h2>Seu próximo<br/>bom corte.</h2><p>Escolha um serviço, uma data e um horário. O resto começa na cadeira.</p></div><Form mode="booking" closedDays={[0]} professionals={["André", "Rafael"]} options={["Corte clássico · R$ 55", "Barba completa · R$ 45", "Ritual Black House · R$ 90"]} title="Simular agendamento"/></section>
  <Location name="Black House" hours="Segunda a sábado · 9h às 20h"/>
  <section className="experienceContact contactSecondary" id="contato"><div><span className="eyebrow">CONVERSA BOA COMEÇA AQUI</span><h2>Fale com a casa.</h2><p>Dúvidas sobre os serviços ou um pedido especial? Deixe sua mensagem.</p></div><Form title="Preparar mensagem"/></section><Footer brand="Black House" demo/>
  </main>; }
