import { Navigation, DemoBar, Photo, Form, Location, Testimonials, Footer, Arrow } from "./Experience";

export const menu = {
  Entradas: [["Burrata do pomar", "Tomates confitados, pesto de manjericão e pão de fermentação natural.", 46], ["Carpaccio Sapore", "Lâminas de filé, alcaparras, rúcula e lascas de parmesão.", 52], ["Croquetas de costela", "Costela de longa cocção e aioli defumado.", 38]],
  Massas: [["Ravioli della nonna", "Massa fresca, ricota, espinafre e manteiga de sálvia.", 74], ["Tagliatelle al ragù", "Ragù de costela preparado lentamente, finalizado com grana padano.", 86]],
  Carnes: [["Filé ao vinho", "Purê rústico, legumes da estação e redução de vinho tinto.", 108], ["Costela da casa", "Cocção de 12 horas, polenta cremosa e farofa de ervas.", 94]],
  Peixes: [["Peixe do dia", "Peixe grelhado, arroz negro e molho de limão siciliano.", 98], ["Salmão do jardim", "Crosta de ervas, purê de ervilha e vegetais assados.", 104]],
  Sobremesas: [["Tiramisù Sapore", "Mascarpone, café e uma delicada camada de cacau.", 34], ["Panna cotta", "Baunilha, frutas vermelhas e crocante de amêndoas.", 32]],
  Vinhos: [["Casa do Vale · Tinto", "Brasil · Merlot · Taça 150 ml.", 29], ["Colina Serena · Branco", "Brasil · Chardonnay · Garrafa 750 ml.", 128], ["Brisa Rosé", "Brasil · Rosé seco · Garrafa 750 ml.", 116]],
  Coquetéis: [["Negroni da casa", "Gin, vermute rosso, bitter e casca de laranja.", 36], ["Jardim Sapore", "Gin, limão, tônica e alecrim fresco.", 34], ["Brisa de verão · sem álcool", "Maracujá, limão, hortelã e água com gás.", 24]]
};
export function RestaurantNav() { return <Navigation brand="Casa Sapore" home="/exemplos/restaurante" links={[["A casa", "/exemplos/restaurante#historia"], ["Menu", "/exemplos/restaurante/menu"], ["Ambiente", "/exemplos/restaurante#ambiente"], ["Contato", "/exemplos/restaurante#contato"]]} action="/exemplos/restaurante#reserva" actionLabel="Reservar mesa"/>; }

export default function Restaurant({ menuPage = false }) { return <main className="saporePage"><DemoBar name="Casa Sapore"/><RestaurantNav/>{menuPage ? <>
  <section className="menuCover"><span className="eyebrow">À MESA / CASA SAPORE</span><h1>O sabor de<br/><em>ficar mais um pouco.</em></h1><p>Ingredientes da estação. Receitas com memória.<br/>Nossa cozinha, em sete capítulos.</p><span className="menuEdition">MENU DA CASA · EDIÇÃO DEMONSTRATIVA</span></section>
  <nav className="menuCategoryNav" aria-label="Categorias do menu">{Object.keys(menu).map((c, i) => <a key={c} href={`#categoria-${i}`}>{c}</a>)}</nav>
  <div className="menuEditorial">{Object.entries(menu).map(([category, dishes], i) => <section className="menuChapter" key={category} id={`categoria-${i}`}><div className="menuChapterTitle"><span>0{i + 1}</span><h2>{category}</h2></div><div>{dishes.map(([name, description, price]) => <article className="dishRow" key={name}><div><h3>{name}</h3><p>{description}</p></div><span>R$ {price}</span></article>)}</div></section>)}</div><div className="menuFootnote">Valores e rótulos fictícios. Consulte a equipe sobre ingredientes e restrições alimentares.<br/>Bebidas alcoólicas destinadas a maiores de 18 anos.</div><section className="saporeClosing"><h2>Seu lugar à mesa.</h2><a className="refinedBtn" href="/exemplos/restaurante#reserva">Escolher uma data<Arrow/></a></section>
  </> : <>
  <section className="saporeHero"><Photo id="67468" alt="Salão intimista com mesas preparadas e iluminação acolhedora" eager/><div className="saporeHeroCopy"><span className="eyebrow">COZINHA CONTEMPORÂNEA · ALMA ITALIANA</span><h1>À mesa,<br/>o tempo <em>fica.</em></h1><p>Massas feitas à mão, ingredientes da estação e boas histórias para acompanhar.</p><div className="refinedActions"><a className="refinedBtn" href="#reserva">Reserve sua mesa<Arrow/></a><a className="textButton" href="/exemplos/restaurante/menu">Conheça o menu ↗</a></div></div><span className="saporeHeroNote">FEITO COM TEMPO. SERVIDO COM AFETO.</span></section>
  <section className="saporeStory" id="historia"><span className="eyebrow">BENVENUTI A CASA</span><h2>Uma casa de portas abertas.<br/>Uma cozinha <em>de verdade.</em></h2><div><p>A Casa Sapore nasceu do desejo de reunir pessoas ao redor de uma mesa. Da massa aberta todas as manhãs ao último café, cada detalhe convida a desacelerar.</p><p>Sabores italianos encontram ingredientes brasileiros em uma cozinha que respeita a estação e guarda espaço para a surpresa.</p><a className="textButton" href="/exemplos/restaurante/menu">Explore nosso menu <Arrow/></a></div></section>
  <section className="saporeFeature"><Photo id="1279330" alt="Massa italiana preparada com molho e ervas"/><div><span className="eyebrow">DA NOSSA COZINHA</span><h2>Simples na essência.<br/><em>Memorável no sabor.</em></h2><p>Ravioli de ricota, manteiga de sálvia e um toque de parmesão. A delicadeza de uma receita feita à mão.</p><a className="refinedBtn" href="/exemplos/restaurante/menu">Ver menu completo<Arrow/></a></div></section>
  <section className="atmosphere" id="ambiente"><div className="sectionHeading"><div><span className="eyebrow">LUZ BAIXA. BOA COMPANHIA.</span><h2>Um lugar para ficar.</h2></div><p>Um jantar a dois, uma celebração ou só a vontade de comer bem.</p></div><div className="atmosphereGrid"><Photo id="67468" alt="Salão iluminado com mesas cuidadosamente preparadas"/><Photo id="260922" alt="Mesas do restaurante prontas para receber convidados"/><Photo id="941861" alt="Ambiente acolhedor para um jantar especial"/></div></section>
  <section className="chefStory"><Photo id="887827" alt="Chef preparando um prato na cozinha"/><div><span className="eyebrow">QUEM ASSINA A COZINHA</span><h2>Memória, técnica<br/>e um pouco de intuição.</h2><p>Para o chef fictício Matteo Costa, cozinhar é transformar ingredientes simples em encontros especiais. Suas receitas partem da tradição italiana e ganham novos caminhos com os sabores da estação.</p><span className="chefSignature">Matteo Costa</span><small>CHEF / CASA SAPORE</small></div></section>
  <Testimonials quotes={[["A massa fresca e a luz do salão fizeram nosso jantar especial.", "Marina A."], ["Atendimento atencioso, do primeiro vinho à sobremesa.", "Pedro L."], ["Daqueles lugares em que a conversa pede mais um café.", "Clara M."]]}/>
  <section className="experienceContact" id="reserva"><div><span className="eyebrow">UM ENCONTRO MARCADO</span><h2>Reserve um tempo<br/><em>para estar à mesa.</em></h2><p>Escolha a data e o tamanho do seu grupo. Para ocasiões especiais, deixe uma observação.</p><small>Reserva demonstrativa, sem bloqueio de mesas.</small></div><Form mode="reservation" closedDays={[1]} options={["2 pessoas", "3 pessoas", "4 pessoas", "5 pessoas", "6 pessoas"]} title="Simular reserva"/></section>
  <Location name="Casa Sapore" hours="Terça a domingo · 18h às 23h"/>
  <section className="experienceContact contactSecondary" id="contato"><div><span className="eyebrow">FALE COM A CASA</span><h2>Uma ocasião especial?</h2><p>Conte sobre seu evento, preferências ou dúvidas.</p></div><Form title="Preparar mensagem"/></section>
  </>}<Footer brand="Casa Sapore" demo/></main>; }
