import test from 'node:test';
import assert from 'node:assert/strict';
import { testStore } from './postgres-test-store.mjs';
import { encryptToken } from '../server/admin/meta.mjs';
import { metaAdsOperations } from '../server/admin/meta-ads-api.mjs';
import { validateDraft } from '../server/admin/meta-ads-service.mjs';
import { migrate } from '../server/admin/migrations.mjs';
import { planCampaign, aiAvailability } from '../server/admin/meta-ads-ai.mjs';
const env={NODE_ENV:'production',ADMIN_SITE_ORIGIN:'https://marquesano.com.br',META_APP_ID:'123',META_APP_SECRET:'fixture-secret',META_REDIRECT_URI:'https://marquesano.com.br/api/admin/meta/callback'};
const draft={name:'Campaign',objective:'OUTCOME_TRAFFIC',daily_budget:1000,landing_page:'https://marquesano.com.br',text:'Texto',title:'Titulo',cta:'LEARN_MORE',page_id:'44',image_hash:'a'.repeat(32),optimization_goal:'LINK_CLICKS',special_ad_categories:[],targeting:{geo_locations:{countries:['BR']},age_min:18,age_max:65}};
async function fixture(t) {
  const {store,db}=await testStore();t.after(()=>store.close());await store.createOwner('test@example.invalid','a-test-password-123');const user=await store.authenticate('test@example.invalid','a-test-password-123');
  await db.prepare('UPDATE meta_connection SET app_id=?,token_ciphertext=?,expires_at=?,account_json=? WHERE id=1').run('123',encryptToken('fixture-token',env),Date.now()+600000,JSON.stringify({id:'act_789'}));
  const calls=[];let failure=false,manage=true;
  const row={id:'11',account_id:'789',name:'Existing',status:'PAUSED',effective_status:'PAUSED'};
  const fetcher=async(url,options={})=>{
    const path=new URL(url).pathname.replace(/^\/v\d+\.0\//,'');calls.push({path,method:options.method||'GET',body:options.body});
    if(failure)return Response.json({error:{code:190,message:'fixture-token secret'}},{status:401});
    if(options.method==='POST'){if(path.endsWith('adimages'))return Response.json({images:{x:{hash:'a'.repeat(32),url:'https://example.invalid/image.png'}}});return Response.json({id:String(100+calls.length),success:true},{headers:{'x-fb-trace-id':'trace-test'}});}
    if(path==='me/permissions')return Response.json({data:[{permission:'ads_read',status:'granted'},...(manage?[{permission:'ads_management',status:'granted'}]:[])]});
    if(path==='act_789')return Response.json({id:'act_789',name:'Test',currency:'BRL'});
    if(path==='11')return Response.json(row);
    if(path.endsWith('/campaigns'))return Response.json({data:[row]});
    if(path.endsWith('/insights'))return Response.json({data:[{campaign_id:'11',spend:'2.50',clicks:'3',date_start:'2026-09-01'}]});
    return Response.json({data:[]});
  };
  const api=(path='',body,actor=user,origin=env.ADMIN_SITE_ORIGIN)=>metaAdsOperations(new Request('https://marquesano.com.br/api/admin/meta-ads/'+path,{method:body?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),path.split('?')[0].split('/').filter(Boolean),actor,store.repository,{env,fetcher});
  return {store,db,user,api,calls,row,fail:()=>failure=true,readOnly:()=>manage=false};
}
test('reads campaign metrics without inventing missing reach, sync only GETs Meta',async t=>{const f=await fixture(t);const r=await f.api('sync',{});assert.equal(r.campaigns[0].metrics.spend,2.5);assert.equal(r.campaigns[0].metrics.reach,null);assert(f.calls.every(c=>c.method==='GET'));assert.equal((await f.db.prepare('SELECT count(*) n FROM meta_campaign_snapshots').get()).n,1);});
test('local drafts do not POST to Meta and never retain unknown fields',async t=>{const f=await fixture(t);await f.api('drafts',draft);assert.equal((await f.api('drafts')).rows.length,1);assert(f.calls.every(c=>c.method==='GET'));await assert.rejects(f.api('drafts',{...draft,access_token:'secret'}));});
test('confirmed creation makes all delivery objects PAUSED; replay and concurrent execute do not duplicate',async t=>{const f=await fixture(t);const p=await f.api('prepare',{action:'create',draft});assert(!f.calls.some(c=>c.method==='POST'));const out=await Promise.allSettled([f.api('execute',{confirmed:true,confirmation:p.confirmation}),f.api('execute',{confirmed:true,confirmation:p.confirmation})]);assert.equal(out.filter(x=>x.status==='fulfilled').length,1);const writes=f.calls.filter(c=>c.method==='POST');assert.equal(writes.length,4);for(const c of writes.filter(c=>!c.path.endsWith('adcreatives')))assert.equal(c.body.get('status'),'PAUSED');});
test('activation requires explicit user-bound confirmation, no write on missing confirmation',async t=>{const f=await fixture(t);await assert.rejects(f.api('execute',{confirmed:false}));const p=await f.api('prepare',{action:'status',kind:'campaigns',resource:'11',status:'ACTIVE'});await assert.rejects(f.api('execute',{confirmed:true,confirmation:p.confirmation},{id:'other',role:'OWNER'}));assert(!f.calls.some(c=>c.method==='POST'));await f.api('execute',{confirmed:true,confirmation:p.confirmation});assert.equal(f.calls.find(c=>c.method==='POST').body.get('status'),'ACTIVE');});
test('changed resource invalidates approved mutation without a Meta write',async t=>{const f=await fixture(t);const p=await f.api('prepare',{action:'status',kind:'campaigns',resource:'11',status:'ACTIVE'});f.row.name='Changed';await assert.rejects(f.api('execute',{confirmed:true,confirmation:p.confirmation}));assert(!f.calls.some(c=>c.method==='POST'));});
test('image upload uses server credentials and deduplicates bytes per account',async t=>{const f=await fixture(t);const image={name:'Test',format:'1:1',bytes:Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),Buffer.alloc(24)]).toString('base64')};await f.api('upload',image);await f.api('upload',image);assert.equal(f.calls.filter(c=>c.method==='POST').length,1);await assert.rejects(f.api('upload',{...image,bytes:Buffer.from('<svg onload="alert()">').toString('base64')}));});
test('provider errors are friendly and never expose token text',async t=>{const f=await fixture(t);f.fail();await assert.rejects(f.api(),e=>!e.message.includes('fixture-token')&&e.status===409);});
for(const role of ['OWNER','ADMIN','MARKETING','SALES','VIEWER'])test('module permissions '+role,async t=>{const f=await fixture(t);if(['OWNER','ADMIN'].includes(role))assert((await f.api('status',undefined,{...f.user,role})).account);else await assert.rejects(f.api('status',undefined,{...f.user,role}),e=>e.status===403);});
test('origin rejects hostile requests before network access',async t=>{const f=await fixture(t);await assert.rejects(f.api('sync',{},f.user,'https://evil.example'),e=>e.status===403);assert.equal(f.calls.length,0);});
test('location lookup is read-only and rejects empty searches',async t=>{const f=await fixture(t);await assert.rejects(f.api('locations?q='));assert.deepEqual((await f.api('locations?q=Sao')).rows,[]);assert(f.calls.some(c=>c.path==='search'));assert(f.calls.every(c=>c.method==='GET'));});
for(const mode of ['missing','invalid','unselected'])test('token/account condition '+mode,async t=>{const f=await fixture(t);if(mode==='missing')await f.db.exec('UPDATE meta_connection SET token_ciphertext=NULL');if(mode==='invalid')await f.db.exec("UPDATE meta_connection SET token_ciphertext='bad'");if(mode==='unselected')await f.db.exec('UPDATE meta_connection SET account_json=NULL');await assert.rejects(f.api());assert(!f.calls.some(c=>c.method==='POST'));});
test('management scope is required for writes, reads remain available',async t=>{const f=await fixture(t);f.readOnly();assert.equal((await f.api('status')).manage,false);await assert.rejects(f.api('prepare',{action:'create',draft}),e=>e.status===403);});
test('expired confirmation is rejected and account ownership is checked',async t=>{const f=await fixture(t);const p=await f.api('prepare',{action:'create',draft});await f.db.exec('UPDATE meta_action_log SET expires=0');await assert.rejects(f.api('execute',{confirmed:true,confirmation:p.confirmation}),e=>e.status===409);f.row.account_id='999';await assert.rejects(f.api('prepare',{action:'status',kind:'campaigns',resource:'11',status:'ACTIVE'}),e=>e.status===403);assert(!f.calls.some(c=>c.method==='POST'));});
test('copy always requests PAUSED; no active duplication',async t=>{const f=await fixture(t);const p=await f.api('prepare',{action:'duplicate',kind:'campaigns',resource:'11'});await f.api('execute',{confirmed:true,confirmation:p.confirmation});const call=f.calls.find(c=>c.method==='POST');assert.equal(call.path,'11/copies');assert.equal(call.body.get('status_option'),'PAUSED');});
test('migration 9 idempotent and preserves drafts and existing OWNER',async t=>{const f=await fixture(t);await f.api('drafts',draft);await migrate(f.db);await migrate(f.db);assert.equal((await f.api('drafts')).rows.length,1);assert.equal((await f.db.prepare('SELECT count(*) n FROM schema_migrations').get()).n,9);assert(await f.store.authenticate('test@example.invalid','a-test-password-123'));});
test('draft validation rejects unsafe destination, missing IDs, negative budget, no target',()=>{for(const changes of [{landing_page:'javascript:alert(1)'},{page_id:''},{daily_budget:-1},{targeting:{}},{image_hash:''}])assert.throws(()=>validateDraft({...draft,...changes}));});
test('AI disabled without provider; mocked provider can only produce a local plan',async()=>{assert.equal(aiAvailability({}).text,false);await assert.rejects(planCampaign({},{}));let payload;const text=await planCampaign({product:'Site',objective:'Leads',budget:'10',region:'BR'},{OPENAI_API_KEY:'fixture',OPENAI_META_ADS_MODEL:'configured-model'},async(u,o)=>{assert.equal(u,'https://api.openai.com/v1/responses');payload=JSON.parse(o.body);return Response.json({output:[{type:'message',content:[{type:'output_text',text:'Plano para revisão'}]}]});});assert.equal(text,'Plano para revisão');assert.equal(payload.store,false);assert(!payload.tools);});
