import test from 'node:test';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import { NextRequest } from 'next/server.js';
import { testStore, testDatabase } from './postgres-test-store.mjs';
import { migrate } from '../server/admin/migrations.mjs';
import { handleAdminApi } from '../server/admin/api.mjs';
import { canAccess, createAdminStore } from '../server/admin/core.mjs';
import { salesOperations } from '../server/admin/sales-api.mjs';
import { salesEmail, salesWhatsApp } from '../server/admin/sales-mail.mjs';
import { handleMercadoPagoWebhook } from '../server/admin/mercadopago-webhook.mjs';

const stamp='2026-09-22T12:00:00.000Z',now=Date.parse(stamp);
const env={NODE_ENV:'production',DATABASE_URL:'postgresql://isolated/test',ADMIN_SITE_ORIGIN:'https://marquesano.com.br',MERCADOPAGO_ACCESS_TOKEN:'mock',MERCADOPAGO_WEBHOOK_SECRET:'mock-secret',RESEND_API_KEY:'mock-mail',CONTACT_FROM_EMAIL:'support@example.invalid'};
const subscription=(id='sub1',extra={})=>({id,plan_id:'basico',status:'authorized',next_payment_date:'2026-09-25T12:00:00.000Z',payer_email:'buyer@example.invalid',updated_at:now,created_at:stamp,amount_cents:9900,currency:'BRL',cycles:12,external_reference:'reference-'+id,...extra});
const payment=(id='pay1',extra={})=>({id,subscription_id:'sub1',invoice_id:null,status:'approved',status_detail:'accredited',amount_cents:9900,currency:'BRL',paid_at:stamp,created_at:stamp,updated_at:now,...extra});
async function fixture(t){let clock=now;const {store,db}=await testStore(()=>clock);t.after(()=>store.close());return {store,db,repo:store.repository,advance:ms=>{clock+=ms;},apply:(s,p,key)=>store.repository.billing.apply({event:{key:key||`${s?.id}:${s?.status}:${p?.id}:${p?.status}:${s?.updated_at}:${p?.updated_at}`,topic:p?'payment':'subscription_preapproval',id:p?.id||s.id},subscription:s,payment:p})};}
const count=async(db,table)=>Number((await db.prepare(`SELECT count(*) n FROM ${table}`).get()).n);

test('migration upgrades existing billing rows without replacing plans or sending historical mail',async t=>{
  const db=await testDatabase();t.after(()=>db.close());
  await db.exec("CREATE TABLE schema_migrations(version BIGINT PRIMARY KEY,applied_at TEXT NOT NULL); INSERT INTO schema_migrations VALUES(7,'skip-for-upgrade-test')");
  await createAdminStore('postgresql://isolated/test',()=>now,{open:async()=>db});
  await db.prepare('INSERT INTO mp_subscriptions VALUES(?,?,?,?,?,?)').run('old','basico','authorized',null,'old@example.invalid',now);
  await db.prepare('INSERT INTO mp_payments VALUES(?,?,?,?,?,?,?,?,?)').run('old-payment','old',null,'approved',null,12345,'BRL',stamp,now);
  await db.prepare('INSERT INTO checkout_attempts VALUES(?,?,?,?,?,?,?,?)').run('old-reference','fingerprint','basico',12345,'authorized',now,'2026-09-checkout-12-months','old');
  const plans=await db.prepare('SELECT * FROM subscription_plans ORDER BY id').all();
  await db.exec('DELETE FROM schema_migrations WHERE version=7');await migrate(db);await migrate(db);
  const old=await db.prepare("SELECT * FROM mp_subscriptions WHERE id='old'").get();
  assert.equal(Number(old.amount_cents),12345);assert.equal(Number(old.cycles),12);assert.equal(old.created_at,stamp);assert.equal(old.external_reference,'old-reference');
  assert.equal(await count(db,'mp_payments'),1);assert.equal(await count(db,'sales_notifications'),0);assert.deepEqual(await db.prepare('SELECT * FROM subscription_plans ORDER BY id').all(),plans);
});

test('pagination and invalid filters never lose or invent subscriptions',async t=>{const f=await fixture(t);for(let i=0;i<26;i++)await f.apply(subscription('s'+String(i).padStart(2,'0')));const a=await f.repo.sales.list(),b=await f.repo.sales.list(new URLSearchParams({page:'2'}));assert.equal(a.rows.length,25);assert.equal(b.rows.length,1);assert.equal(new Set([...a.rows,...b.rows].map(r=>r.id)).size,26);for(const values of [{plan:'__proto__'},{status:'anything'},{page:'-1'},{start:'2026-02-31'},{start:'2026-10-10',end:'2026-09-01'}])await assert.rejects(f.repo.sales.list(new URLSearchParams(values)));});

test('historic payments remain visible when subscription currency was not recorded',async t=>{const f=await fixture(t);await f.apply(subscription('sub1',{currency:null,amount_cents:null}),payment());const d=await f.repo.sales.detail('sub1');assert.equal(Number(d.record.total_paid),9900);assert.equal(d.record.total_paid_currency,'BRL');});

test('new subscription: snapshots and one welcome notification; migration idempotent',async t=>{const f=await fixture(t);await f.apply(subscription());await migrate(f.db);await migrate(f.db);const d=await f.repo.sales.detail('sub1');assert.equal(d.record.amount_cents,9900);assert.equal(d.record.cycles,12);assert.equal(d.communications.length,1);assert.equal(d.communications[0].type,'welcome');assert.equal(await count(f.db,'subscription_plans'),3);});
test('approved payment updates received revenue, paid cycles and remaining forecast',async t=>{const f=await fixture(t);await f.apply(subscription(),payment());const d=await f.repo.sales.detail('sub1');assert.equal(Number(d.record.total_paid),9900);assert.equal(Number(d.record.paid_cycles),1);assert.equal(Number(d.record.remaining_cycles),11);assert.equal(Number(d.record.remaining_amount),108900);assert.equal(Number((await f.repo.sales.summary()).revenue_month),9900);assert.equal(d.communications.filter(n=>n.type==='approved').length,1);});
test('rejected payment is not received revenue and queues friendly notification',async t=>{const f=await fixture(t);await f.apply(subscription(),payment('pay1',{status:'rejected',paid_at:null,status_detail:'technical-refusal'}));assert.equal(Number((await f.repo.sales.summary()).revenue_month),0);assert.equal((await f.repo.sales.detail('sub1')).communications.filter(n=>n.type==='rejected').length,1);});
test('cancelled subscription removes MRR, preserves history and queues cancellation once',async t=>{const f=await fixture(t);await f.apply(subscription(),payment());const cancelled=subscription('sub1',{status:'cancelled',cancelled_at:stamp,next_payment_date:null,updated_at:now+1});await f.apply(cancelled);await f.apply(cancelled);const d=await f.repo.sales.detail('sub1');assert.equal(d.record.cancelled_at,stamp);assert.equal(d.payments.length,1);assert.equal(d.communications.filter(n=>n.type==='cancelled').length,1);assert.equal(Number((await f.repo.sales.summary()).mrr),0);});
test('upcoming dates use authoritative next_payment_date; cancelled excluded',async t=>{const f=await fixture(t);await f.apply(subscription());await f.apply(subscription('today',{next_payment_date:stamp}));await f.apply(subscription('later',{next_payment_date:'2026-10-15T12:00:00.000Z'}));await f.apply(subscription('cancelled',{status:'cancelled',next_payment_date:stamp}));assert.equal(Number((await f.repo.sales.upcoming(new URLSearchParams({due:'today'}))).total),1);assert.equal(Number((await f.repo.sales.upcoming(new URLSearchParams({due:'7'}))).total),2);assert.equal(Number((await f.repo.sales.upcoming()).total),3);});
test('duplicate billing event and concurrent delivery preserve one payment and notification',async t=>{const f=await fixture(t);await Promise.all([f.apply(subscription(),payment()),f.apply(subscription(),payment())]);assert.equal(await count(f.db,'mp_payments'),1);assert.equal(await count(f.db,'mp_webhook_events'),1);assert.equal(await count(f.db,'sales_notifications'),2);});
test('out-of-order events cannot regress status or enqueue obsolete emails',async t=>{const f=await fixture(t);await f.apply(subscription('sub1',{status:'cancelled',updated_at:now+10}),payment('pay1',{updated_at:now+10}));await f.apply(subscription(),payment('pay1',{status:'rejected',paid_at:null}));const d=await f.repo.sales.detail('sub1');assert.equal(d.record.status,'cancelled');assert.equal(d.payments[0].status,'approved');assert(!d.communications.some(n=>['welcome','rejected'].includes(n.type)));});
test('duplicate email dispatch and concurrent workers send each notification once',async t=>{const f=await fixture(t);await f.apply(subscription());let calls=0;const fetcher=async(url,options)=>{calls++;assert.equal(url,'https://api.resend.com/emails');assert.match(options.headers['Idempotency-Key'],/^sales-/);return Response.json({id:'email1'});};await Promise.all([f.repo.billing.notifications.dispatch({env,fetcher}),f.repo.billing.notifications.dispatch({env,fetcher})]);await f.repo.billing.notifications.dispatch({env,fetcher});assert.equal(calls,1);assert.equal((await f.repo.sales.detail('sub1')).communications[0].state,'SENT');});
test('uncertain email retries immutable payload/key then stops before provider key expiry',async t=>{const f=await fixture(t);await f.apply(subscription());const calls=[];const fetcher=async(url,options)=>{calls.push(options);throw Error('timeout');};await f.repo.billing.notifications.dispatch({env,fetcher});f.advance(61000);await f.db.prepare("UPDATE mp_subscriptions SET amount_cents=1 WHERE id='sub1'").run();await f.repo.billing.notifications.dispatch({env:{...env,CONTACT_FROM_EMAIL:'changed@example.invalid'},fetcher});assert.equal(calls[0].body,calls[1].body);assert.equal(calls[0].headers['Idempotency-Key'],calls[1].headers['Idempotency-Key']);f.advance(24*3600000);await f.repo.billing.notifications.dispatch({env,fetcher});assert.equal(calls.length,2);assert.equal((await f.repo.sales.detail('sub1')).communications[0].state,'REVIEW');});
test('absent email provider leaves durable pending notification',async t=>{const f=await fixture(t);await f.apply(subscription());assert.equal((await f.repo.billing.notifications.dispatch({env:{}})).configured,false);assert.equal((await f.repo.sales.detail('sub1')).communications[0].state,'PENDING');});
test('monthly revenue excludes previous month/pending/refunded and subtracts partial refund',async t=>{const f=await fixture(t);await f.apply(subscription(),payment('partial',{refunded_cents:900}));await f.apply(null,payment('previous',{paid_at:'2026-08-20T12:00:00.000Z'}));await f.apply(null,payment('pending',{status:'pending',paid_at:null}));await f.apply(null,payment('refunded',{status:'refunded',refunded_cents:9900}));assert.equal(Number((await f.repo.sales.summary()).revenue_month),9000);});
test('three public plan filters preserve existing internal IDs',async t=>{const f=await fixture(t);for(const [i,id] of ['basico','intermediario','professional'].entries())await f.apply(subscription('s'+i,{plan_id:id}));for(const [code,id] of [['basico','basico'],['professional','intermediario'],['business','professional']]){const data=await f.repo.sales.list(new URLSearchParams({plan:code}));assert.equal(data.rows.length,1);assert.equal(data.rows[0].plan_id,id);}});
test('status, payment, date and email filters constrain actual subscriptions',async t=>{const f=await fixture(t);await f.apply(subscription(),payment());await f.apply(subscription('cancelled',{status:'cancelled',payer_email:'other@example.invalid'}),payment('pay2',{subscription_id:'cancelled',status:'rejected',paid_at:null}));assert.equal((await f.repo.sales.list(new URLSearchParams({status:'cancelled'}))).rows[0].id,'cancelled');assert.equal((await f.repo.sales.list(new URLSearchParams({payment:'approved',q:'buyer',start:'2026-09-22',end:'2026-09-22'}))).rows[0].id,'sub1');assert.equal((await f.repo.sales.list(new URLSearchParams({start:'2026-09-23'}))).rows.length,0);});
test('empty report has zero real counts and no invented records',async t=>{const f=await fixture(t);assert.equal(Number((await f.repo.sales.list()).total),0);assert.equal(Number((await f.repo.sales.summary()).active),0);assert.equal(Number((await f.repo.sales.summary()).revenue_month),0);});
test('unknown historical amount/date stay unknown rather than using current catalog price',async t=>{const f=await fixture(t);await f.apply(subscription('sub1',{amount_cents:null,currency:null,cycles:null,created_at:null}));const d=await f.repo.sales.detail('sub1');assert.equal(d.record.amount_cents,null);assert.equal(d.record.created_at,null);assert.equal(d.record.remaining_amount,null);assert.equal(Number((await f.repo.sales.summary()).unknown_amounts),1);});

async function providerFixture(t){const f=await fixture(t);await f.db.prepare("UPDATE subscription_plans SET mercadopago_plan_id='remote_plan' WHERE id='basico'").run();const remote={id:'sub1',collector_id:42,preapproval_plan_id:'remote_plan',status:'authorized',payer_email:'buyer@example.invalid',date_created:stamp,last_modified:stamp,next_payment_date:'2026-10-22T12:00:00.000Z',auto_recurring:{transaction_amount:99,currency_id:'BRL',repetitions:12}};const calls=[];let mails=0;const fetcher=async(url,options={})=>{calls.push({url,method:options.method});if(url==='https://api.resend.com/emails'){mails++;return Response.json({id:'mail'+mails});}assert.notEqual(options.method,'POST');const path=new URL(url).pathname;const resources={'/users/me':{id:42},'/preapproval/sub1':remote,'/authorized_payments/search':{paging:{total:1},results:[{id:'invoice1'}]},'/authorized_payments/invoice1':{id:'invoice1',preapproval_id:'sub1',status:'processed',debit_date:stamp,last_modified:stamp,payment:{id:'payment1'}},'/v1/payments/payment1':{id:'payment1',collector_id:42,status:'approved',status_detail:'accredited',transaction_amount:99,currency_id:'BRL',date_created:stamp,date_approved:stamp,date_last_updated:stamp,payment_method_id:'master',card:{last_four_digits:'1234',card_number:'NEVER STORE',security_code:'NEVER STORE'},card_token_id:'NEVER STORE'}};assert(resources[path],path);return Response.json(resources[path]);};return {...f,remote,fetcher,calls,get mails(){return mails;}};}
test('sync reads only existing subscriptions, updates next date and deduplicates payments',async t=>{const f=await providerFixture(t);await f.apply(subscription('sub1',{status:'pending',updated_at:now-1}));const req=()=>new Request('https://marquesano.com.br/api/admin/vendas/sync',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});const actor={role:'OWNER'};const first=await salesOperations(req(),['sync'],actor,f.repo,{env,fetcher:f.fetcher});assert.equal(first.verified,1);assert.equal(first.new_payments,1);assert.equal(first.errors.length,0);const second=await salesOperations(req(),['sync'],actor,f.repo,{env,fetcher:f.fetcher});assert.equal(second.new_payments,0);const d=await f.repo.sales.detail('sub1');assert.equal(d.record.next_payment_date,f.remote.next_payment_date);assert.equal(d.payments[0].last_four,'1234');assert(!JSON.stringify(d).includes('NEVER STORE'));assert.equal(await count(f.db,'mp_subscriptions'),1);});
test('sync provider errors return safe counts without inventing successful updates',async t=>{const f=await fixture(t);await f.apply(subscription());const result=await salesOperations(new Request('https://marquesano.com.br/api/admin/vendas/sync',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}),['sync'],{role:'ADMIN'},f.repo,{env,fetcher:async()=>{throw Error('secret');}});assert.equal(result.errors.length,1);assert.equal(result.updated,0);assert(!JSON.stringify(result).includes('secret'));});
test('real signed webhook handler confirms resource, queues and deduplicates email',async t=>{const f=await providerFixture(t);const req=()=>{const id='sub1',rid='test-request',ts='12345',sig=createHmac('sha256',env.MERCADOPAGO_WEBHOOK_SECRET).update(`id:${id};request-id:${rid};ts:${ts};`).digest('hex');return new Request('https://marquesano.com.br/api/mercadopago/webhook?data.id=sub1',{method:'POST',headers:{'content-type':'application/json','x-request-id':rid,'x-signature':`ts=${ts},v1=${sig}`},body:JSON.stringify({type:'subscription_preapproval',data:{id}})});};for(let i=0;i<2;i++)assert.equal((await handleMercadoPagoWebhook(req(),{env,store:f.store,fetcher:f.fetcher})).status,200);assert.equal(f.mails,1);assert.equal(await count(f.db,'sales_notifications'),1);});
for(const role of ['OWNER','ADMIN','SALES','MARKETING','VIEWER'])test('sales API role '+role,async t=>{const f=await fixture(t);const response=await handleAdminApi(new NextRequest('https://marquesano.com.br/api/admin/vendas'),['vendas'],{env,store:{...f.store,getSession:async()=>({id:'test',role})}});const allowed=['OWNER','ADMIN'].includes(role);assert.equal(response.status,allowed?200:403);assert.equal(canAccess(role,'vendas'),allowed);});
test('sales API retains authentication and CSRF protection',async t=>{const f=await fixture(t);assert.equal((await handleAdminApi(new NextRequest('https://marquesano.com.br/api/admin/vendas'),['vendas'],{env,store:f.store})).status,401);assert.equal((await handleAdminApi(new NextRequest('https://marquesano.com.br/api/admin/vendas/sync',{method:'POST',headers:{origin:'https://evil.example'},body:'{}'}),['vendas','sync'],{env,store:{...f.store,getSession:async()=>({role:'OWNER'})}})).status,403);});
test('all four responsive email templates escape names and contain real WhatsApp and legal links',()=>{for(const type of ['welcome','approved','rejected','cancelled']){const result=salesEmail(type,{...subscription(),plan_name:'Básico',name:'<script>alert(1)</script>',payment_amount:9900,payment_date:stamp,cancelled_at:stamp,status_detail:'CC_TECHNICAL_SECRET'});assert(result.html.includes('viewport'));assert(!result.html.includes('<script>'));assert(!result.html.includes('CC_TECHNICAL_SECRET'));assert(result.html.includes('12 meses'));assert(result.html.includes('https://wa.me/5511940702998'));assert(result.html.includes('/termos-de-servico'));assert(result.html.includes('/politica-de-privacidade'));assert(result.text.includes('Mercado Pago'));}assert(salesWhatsApp().includes('5511940702998'));});
