import test from 'node:test';
import assert from 'node:assert/strict';
import { NextRequest } from 'next/server.js';
import { testStore } from './postgres-test-store.mjs';
import { handleAdminApi } from '../server/admin/api.mjs';
import { migrate } from '../server/admin/migrations.mjs';

const pass='test-user-password-123',newPass='new-user-password-456';
const env={NODE_ENV:'production',DATABASE_URL:'postgresql://isolated/test',ADMIN_SITE_ORIGIN:'https://marquesano.com.br'};
const body=(extra={})=>({name:'Usuário de teste',email:'person@example.invalid',role:'VIEWER',active:true,password:pass,confirm_password:pass,...extra});
async function fixture(t){const f=await testStore();t.after(()=>f.store.close());await f.store.createOwner('owner@example.invalid',pass);const owner=await f.store.authenticate('owner@example.invalid',pass);return {...f,owner,users:f.store.repository.users};}
async function api(f,actor,path='',method='GET',data){const request=new NextRequest(env.ADMIN_SITE_ORIGIN+'/api/admin/usuarios'+path,{method,headers:{origin:env.ADMIN_SITE_ORIGIN,'content-type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});return handleAdminApi(request,['usuarios',...path.split('/').filter(Boolean)],{env,store:{...f.store,getSession:async()=>actor}});}

test('list users: name, creation, last login and no hash; migrations idempotent',async t=>{const f=await fixture(t);await f.store.repository.audit(f.owner,'login','auth',f.owner.id);await migrate(f.db);const res=await api(f,f.owner);assert.equal(res.status,200);const list=await res.json();assert.equal(list.rows.length,1);assert(list.rows[0].created_at);assert(list.rows[0].last_login);assert('name' in list.rows[0]);assert(!JSON.stringify(list).includes('password'));});
test('create user with existing scrypt mechanism, normalized email and audit',async t=>{const f=await fixture(t);const res=await api(f,f.owner,'','POST',body({email:' PERSON@EXAMPLE.INVALID '}));assert.equal(res.status,200);const {id}=await res.json();const row=await f.db.prepare('SELECT * FROM users WHERE id=?').get(id);assert.match(row.password_hash,/^scrypt\$[a-f0-9]{32}\$[a-f0-9]{128}$/);assert.equal(row.email,'person@example.invalid');assert.equal(row.name,'Usuário de teste');assert(await f.store.authenticate(row.email,pass));assert.equal((await f.db.prepare("SELECT action FROM audit_log WHERE entity_id=?").get(id)).action,'user_created');});
test('duplicate email including case and concurrent creation rejected safely',async t=>{const f=await fixture(t);const results=await Promise.all([api(f,f.owner,'','POST',body()),api(f,f.owner,'','POST',body({email:'PERSON@example.invalid'}))]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);assert.equal(Number((await f.db.prepare('SELECT count(*) n FROM users').get()).n),2);});
test('invalid email, role, weak password, mismatch and oversized password rejected',async t=>{const f=await fixture(t);for(const data of [body({email:'bad'}),body({role:'ROOT'}),body({password:'short',confirm_password:'short'}),body({confirm_password:'different'}),body({password:'x'.repeat(257),confirm_password:'x'.repeat(257)})])assert.equal((await api(f,f.owner,'','POST',data)).status,400);});
test('edit name/email preserves hash; profile endpoint refuses password fields',async t=>{const f=await fixture(t);const {id}=await f.users.save(body(),f.owner);const old=await f.db.prepare('SELECT password_hash FROM users WHERE id=?').get(id);assert.equal((await api(f,f.owner,'/'+id,'PATCH',{name:'Novo nome',email:'new@example.invalid',role:'VIEWER',active:true})).status,200);assert.deepEqual(await f.db.prepare('SELECT password_hash FROM users WHERE id=?').get(id),old);assert(await f.store.authenticate('new@example.invalid',pass));assert.equal((await api(f,f.owner,'/'+id,'PATCH',{...body(),password:newPass})).status,400);});
test('role change revokes sessions and writes explicit role audit',async t=>{const f=await fixture(t);const {id}=await f.users.save(body(),f.owner);const token=await f.store.createSession(id);await f.users.save({name:'Test',email:'person@example.invalid',role:'SALES',active:true},f.owner,id);assert.equal(await f.store.getSession(token),null);assert.equal((await f.store.authenticate('person@example.invalid',pass)).role,'SALES');assert(await f.db.prepare("SELECT id FROM audit_log WHERE entity_id=? AND action='user_role_changed'").get(id));});
test('separate password reset invalidates sessions, new password works and old fails',async t=>{const f=await fixture(t);const {id}=await f.users.save(body(),f.owner);const token=await f.store.createSession(id);assert.equal((await api(f,f.owner,'/'+id+'/password','POST',{password:newPass,confirm_password:newPass})).status,200);assert.equal(await f.store.authenticate('person@example.invalid',pass),null);assert(await f.store.authenticate('person@example.invalid',newPass));assert.equal(await f.store.getSession(token),null);const log=JSON.stringify(await f.db.prepare('SELECT * FROM audit_log').all());assert(!log.includes(pass));assert(!log.includes(newPass));assert(!log.includes('scrypt$'));assert(log.includes('user_password_reset'));});
test('password mismatch leaves existing password and session intact',async t=>{const f=await fixture(t);const {id}=await f.users.save(body(),f.owner);const token=await f.store.createSession(id);assert.equal((await api(f,f.owner,'/'+id+'/password','POST',{password:newPass,confirm_password:pass})).status,400);assert(await f.store.authenticate('person@example.invalid',pass));assert(await f.store.getSession(token));});
test('deactivate blocks login and revokes sessions; reactivate permits login',async t=>{const f=await fixture(t);const {id}=await f.users.save(body(),f.owner);const token=await f.store.createSession(id);await f.users.status(id,{active:false},f.owner);assert.equal(await f.store.authenticate('person@example.invalid',pass),null);assert.equal(await f.store.getSession(token),null);await f.users.status(id,{active:true},f.owner);assert(await f.store.authenticate('person@example.invalid',pass));const actions=(await f.db.prepare('SELECT action FROM audit_log WHERE entity_id=?').all(id)).map(r=>r.action);assert(actions.includes('user_deactivated'));assert(actions.includes('user_activated'));});
test('soft delete preserves history, reserves email and blocks reactivation',async t=>{const f=await fixture(t);const {id}=await f.users.save(body(),f.owner);const token=await f.store.createSession(id);assert.equal((await api(f,f.owner,'/'+id+'/delete','POST',{})).status,200);const row=await f.db.prepare('SELECT * FROM users WHERE id=?').get(id);assert(row.deleted_at);assert.equal(Number(row.active),0);assert.equal(await f.store.authenticate(row.email,pass),null);assert.equal(await f.store.getSession(token),null);await assert.rejects(f.users.status(id,{active:true},f.owner),e=>e.status===404);await assert.rejects(f.users.save(body(),f.owner),e=>e.status===409);assert.equal((await f.db.prepare("SELECT count(*) n FROM audit_log WHERE entity_id=?").get(id)).n,2);});
test('last active OWNER protected against removal/deactivation/demotion and self lockout',async t=>{const f=await fixture(t);await assert.rejects(f.users.remove(f.owner.id,f.owner),e=>e.status===409);await assert.rejects(f.users.status(f.owner.id,{active:false},f.owner),e=>e.status===409);await assert.rejects(f.users.save({name:'Owner',email:f.owner.email,role:'ADMIN',active:true},f.owner,f.owner.id),e=>e.status===409);assert(await f.store.authenticate(f.owner.email,pass));});
test('OWNER can manage another OWNER while self lockout remains blocked with two owners',async t=>{const f=await fixture(t);const second=await f.users.save(body({role:'OWNER'}),f.owner);await assert.rejects(f.users.remove(f.owner.id,f.owner),e=>e.status===409);await f.users.remove(second.id,f.owner);assert(await f.store.authenticate(f.owner.email,pass));});
test('ADMIN can manage ordinary accounts but cannot alter OWNER or assign OWNER',async t=>{const f=await fixture(t);await f.users.save(body({role:'ADMIN',email:'admin@example.invalid'}),f.owner);const admin=await f.store.authenticate('admin@example.invalid',pass);assert.equal((await api(f,admin)).status,200);assert.equal((await api(f,admin,'','POST',body())).status,200);assert.equal((await api(f,admin,'','POST',body({email:'other@example.invalid',role:'OWNER'}))).status,403);for(const [action,data] of [['password',{password:newPass,confirm_password:newPass}],['status',{active:false}],['delete',{}]])assert.equal((await api(f,admin,'/'+f.owner.id+'/'+action,'POST',data)).status,403);});
test('stale or forged actor role cannot escalate privileges inside transaction',async t=>{const f=await fixture(t);const {id}=await f.users.save(body(),f.owner);await assert.rejects(f.users.save(body({email:'other@example.invalid'}),{id,role:'OWNER'}),e=>e.status===403);});
for(const role of ['SALES','MARKETING','VIEWER'])test(role+' cannot read or write user management',async t=>{const f=await fixture(t);const user={...f.owner,role};assert.equal((await api(f,user)).status,403);assert.equal((await api(f,user,'','POST',body())).status,403);});
test('own password reset requests fresh login; name-only edit preserves session',async t=>{const f=await fixture(t);const token=await f.store.createSession(f.owner.id);await f.users.save({name:'Owner',email:f.owner.email,role:'OWNER',active:true},f.owner,f.owner.id);assert(await f.store.getSession(token));const result=await f.users.password(f.owner.id,{password:newPass,confirm_password:newPass},f.owner);assert(result.session_invalidated);assert.equal(await f.store.getSession(token),null);});
test('concurrent owners cannot deactivate each other and leave zero owners',async t=>{const f=await fixture(t);await f.users.save(body({role:'OWNER'}),f.owner);const second=await f.store.authenticate('person@example.invalid',pass);const results=await Promise.allSettled([f.users.status(second.id,{active:false},f.owner),f.users.status(f.owner.id,{active:false},second)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(Number((await f.db.prepare("SELECT count(*) n FROM users WHERE role='OWNER' AND active=1").get()).n),1);});
test('database uniqueness itself blocks a case-variant email',async t=>{const f=await fixture(t);await assert.rejects(f.db.prepare('INSERT INTO users(id,email,password_hash,role) VALUES(?,?,?,?)').run('duplicate','OWNER@EXAMPLE.INVALID','unused','VIEWER'),e=>e.code==='23505');});
